[project]
name = 'backend'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.payeer]
path = 'contracts/payeer.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'check_checker',
    'call_checker',
]

[repl.analysis.lint_groups]
